name: schedule-event
on: 
  schedule:
    - cron: "/2 * * * *"  
jobs:
  greeting:
      runs-on: ubuntu-latest
      steps:
        - name: message
          run: echo "welcome to schedule job."
          
