name: schedule-event
on: 
  schedule:
    - cron: "*/05 * * * *"  
jobs:
  greeting:
      runs-on: ubuntu-latest
      concurrency:
        group: deploy
        cancel-in-progress: true
      steps:
        - name: message
          run: echo "welcome to schedule job."
          
